version: 2

jobs:
  build:
    working_directory: ~/iroha-javascript
    docker:
      - image: node:7.7
    steps:
      - checkout
      - restore_cache:
          key: irohajs-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Pre-Dependencies
          command: mkdir ~/iroha-javascript/artifacts
      - run:
          name: Install Dependencies
          command: npm prune && npm cache clean && npm install
      - run:
          name: Test & Build
          command: npm run test:prod && npm run build
      - store_artifacts:
          path: ~/iroha-javascript/dist
          destination: iroha
      - save_cache:
          key: irohajs-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "~/iroha-javascript/node_modules"